### ISSUE TITLE
Enable oci_inventory.py to use Redis to cache inventory

### ISSUE THREAD

**Issue by dmitrypol** [oracle/oci-ansible-modules#14]
## Issue Report

* Currently we can only specify location of `ansible-oci.cache` and `cache_max_age`.  
* As we query large inventories (especially via tags) it might be useful to store results separately to scale the process. 
* Distinct Redis keys can store different results and also have different TTL expirations.  
* Another nice thing about pushing this data into Redis is that it can be exposed via simple API call from something like Flask app.  

I understand that this is not a trivial change.  Ideally there would be come kind of dynamic inventory caching system which would use JSON files, Redis or other data storage systems.  

**Environment**

* Ansible version: 2.7.2

* OCI Python SDK version: 2.1.1

* OCI Ansible Modules version: 1.3.0

**Comment by sivakumart** [comment]
Thanks @dmitrypol for this idea. 

Yes, this is a good idea. When we initially built this project, we were working with Ansible 2.4 (and also had to support customers that use Ansible 2.4), and that only had limited support for custom dynamic inventory scripts, and so our dynamic inventory script uses its own file to cache inventory results. 

Since the release of [Ansible 2.5](https://www.ansible.com/blog/dynamic-inventory-past-present-future), there is support for a feature called ["Inventory Plugins"](https://docs.ansible.com/ansible/2.5/plugins/inventory.html) that abstracts our inventory scripts and makes them pluggable. We have a backlog item to build an OCI inventory plugin. Inventory plugins can then use ["Cache Plugins"](https://docs.ansible.com/ansible/2.5/plugins/cache.html) to cache gathered inventory. So, when the OCI inventory plugin is available, you should be able to use any of the caching mechanisms supported via Cache Plugins (and this includes using [Redis](https://docs.ansible.com/ansible/2.5/plugins/cache/redis.html) for caching).

So please stay tuned, and this feature should be addressed. Thanks

**Comment by nalsaber** [comment]
@dmitrypol we released a dynamic inventory plugin (v 1.12.0) and you can use any caching plugins compatible with Ansible.
