### ISSUE TITLE
oci python sdk required for this module

### ISSUE THREAD

**Issue by ReenaAcharya** [oracle/oci-ansible-modules#18]
Hi,

I am trying to use ansible for oci. However I am getting error as "oci python sdk required for this module". I have installed obi-ansible-modules and oci-python-sdk.

Here is the code:-

- name: Create or Update bucket
  oci_bucket:
    namespace_name: ' '
    compartment_id: ''
    name: 'Test'
    public_access_type: 'NoPublicAccess'
    state: 'present'

Thanks.

**Comment by smak-oracle** [comment]
are you using ansible within firewall? did you try to use virtualenv to install oci-python-sdk?

**Comment by ReenaAcharya** [comment]
I installed python sdk inside virtualenv. Steps used are as follows:-

1. virtualenv -v /python-virtualenv/oci
2. source /python-virtualenv/oci/bin/activate
3. pip install oci
4. git clone https://github.com/oracle/oci-ansible-modules.git
5. cd oci-ansible-modules
6. ./install.py
7. ansible-playbook test.yaml

**Comment by debayan-gupta** [comment]
Which ansible installation are you using? Is it installed in virtualenv or pre-installed in the OS itself? Could you please try to install ansible in your virtualenv in case it is not install and give it a try? Based on the result, the next steps could be taken.

**Comment by sivakumart** [comment]
Hi @ReenaAcharya Could you please let us know if @debayan-gupta's comment helped? Could you also try installing a local version of ansible within the virtual env and using it between steps 3 and 4 in your list of steps at https://github.com/oracle/oci-ansible-modules/issues/18#issuecomment-451060437?

Otherwise, could you please share the following:

* Python
  - insert output of `which python` and `python --version`
* Ansible
  - insert output of `which ansible` and `ansible --version`
* OCI Python SDK version:
  - insert output of `python -c "import oci;print(oci.__version__)"` here
* OCI Ansible Modules version:
  - insert output of `python -c "from ansible.module_utils.oracle import oci_utils; print(oci_utils.__version__)"` here
* Additional debug logs
  - Look at FAQ number 3 in https://oracle-cloud-infrastructure-ansible-modules.readthedocs.io/en/latest/faqs.html

**Comment by sivakumart** [comment]
@ReenaAcharya I am closing this issue as we haven't heard back on this for a while. I assume @debayan-gupta's suggestion of using a virtualenv helped resolve your issue. If no, could you please reopen this issue, and respond to my questions at https://github.com/oracle/oci-ansible-modules/issues/18#issuecomment-454099751? Thanks.

**Comment by plsak** [comment]
Had the same issue, problem was a system installation of ansible (ubuntu -> apt) - although had ansible installed in virtual env as well and `which` was reporting this exec, when using ansible --version it was visible that really used is `/usr/bin/ansible` one (+ the system modules)
So resolution was to uninstall apt version of ansible (using 'pip ansible' version for system seems working fine now).
