### ISSUE TITLE
oci_database_facts: Ability to change facts when pdb is renamed.

### ISSUE THREAD

**Issue by mayanala-coxauto** [oracle/oci-ansible-modules#99]
## Issue Report

If a database has been launched using backup of another database (using source = DB_BACKUP) then there is no ability to chose pdb name. So, the pdb name for new database will be same as the database from which backup was taken. If we rename the pdb name, then oci_database_facts do not reflect these changes causing automation to break. 

**Expected behavior**

Facts should represent or change as per changes made on the databases. 

**Environment**

* OS version:

* Ansible version:

    ansible 2.9.0

* OCI Python SDK version:

    2.6.0

* OCI Ansible Modules version:

    1.14.0

**Ansible playbook to reproduce the issue**

    oci_database_facts

**Comment by AmeyaLokre** [comment]
Hello @mayanala-coxauto . Can you please share the following info:
Did you generate the database and update the pdb_name using Ansible playbook? 
If yes, can you please provide the playbook that you used for encountering this error?
Thank you

**Comment by mayanala-coxauto** [comment]
Hi, please see my answers.

Did you generate the database and update the pdb_name using Ansible playbook?
I launched the DB system using oci_db_system module with source = DB_BACKUP. This module has ability to choose different DB name for target database but not PDB name. When DB system is launched, it gets the PDB name same as source DB. Example: Source DB pdb name is pdb1 and target DB pdb name will be pdb1 as well. We have a need to change target DB pdb name so we changed it using manual steps from sqlplus. Let's say we changed to PDB2. Now this breaks our automation because oci_database_facts show pdbname as PDB1 (instead of PDB2). 

If yes, can you please provide the playbook that you used for encountering this error?
There is no error, I opened this as issue to see if there is a way to reflect facts correctly in case of such changes post DB System launch.

**Comment by mayanala-coxauto** [comment]
In the essence, it seems like facts represent anything that is being done through oracle provided ansible modules. If there are changes done outside these modules, facts do not get updated. This gets complicated because we do not have playbooks for all the operations. In this case, we do not have OCI module to rename pdb.

**Comment by AmeyaLokre** [comment]
Hello @mayanala-coxauto , can you please verify once that the pdb_name of the database is changing when you use the command:
`oci db database get <the database generated using backup>`?
Does this command show the updated pdb_name as pdb2 or does it still show pdb1 ?

**Comment by mayanala-coxauto** [comment]
Hi I just tried oci cli as well and it is showing pdb1 instead of pdb2. Same results from ansible oci_database_facts as well. It should be easily reproducible from your end.

**Comment by AmeyaLokre** [comment]
Hello @mayanala-coxauto , if the pdb_name is shown as pdb1 from both, cli and ansible, then there wouldn't be a problem in the tools. It could be a problem on the server side.
Please try creating the database-backup using the following [cli command](https://docs.cloud.oracle.com/en-us/iaas/tools/oci-cli/2.9.2/oci_cli_docs/cmdref/db/external-backup-job/create.html). If that doesn't work, please reach out to the server-team or comment on this ticket so that we can notify the server team.

**Comment by mayanala-coxauto** [comment]
Hi, I think I'm not being clear. Irrespective of oci cli or ansible module, if the DB is launched with pdbname PDB1, facts shows fine. The issue is "AFTER" DB launch if I login to the database and manually change the pdb name to PDB2 using SQL commands, then facts are not reflecting it. They still show PDB1. Which team should I be approaching for this issue ?

**Comment by AmeyaLokre** [comment]
When the pdbname is being updated using sqlplus, it is not actually changing the pdbname of the database that has been created, which is why ansible modules or oci cli are not reflecting it. You could trying using the [CLI command](https://docs.cloud.oracle.com/en-us/iaas/tools/oci-cli/2.9.2/oci_cli_docs/cmdref/db/external-backup-job/create.html) for creating a new database backup with a different pdbname. <br/>
If that doesn’t work, please Create a Service Request for the database team using the steps mentioned for `Open a support service request` on the [link](https://docs.cloud.oracle.com/en-us/iaas/Content/GSG/Tasks/contactingsupport.htm)
